% options this should have:  kernel regressions or histogram only; use saved
% data or not

%clear all
%close all

% calculate the T--SWC--NEE histograms, kernel regressions, and climate space
% surfaces


sitelist = { UNM_sites.MCon, UNM_sites.PPine, UNM_sites.MCon_SS ...
    UNM_sites.SLand, UNM_sites.GLand, UNM_sites.New_GLand, ...
    UNM_sites.JSav,  UNM_sites.PJ, UNM_sites.PJ_girdle  };
sitelist = {UNM_sites.GLand };
load_stored_data = false;
contour_var = 'NEE';
makefigs = false;
switch contour_var
    case 'NEE'
        surface_data = Kernel_regression_Tim( load_stored_data , sitelist);
    case 'ET'
        surface_data = Kernel_regression_ET( load_stored_data , sitelist);
end

if makefigs
for i = 1:length(sitelist)
    this_site = sitelist{i};  
    [h] = plot( surface_data{i } ) ;
    fprintf('Plotting %s...\n',char(surface_data{i}.sitecode));
    fname = fullfile( 'C:\Code\KernelRegressions\plots', ...                                         
                      sprintf( '%s.png', char( UNM_sites( this_site ) ) ) );
  for j = 1:numel(h)
      fname = fullfile( 'C:\Code\KernelRegressions\plots', ...
          sprintf( '%s.png', [char( UNM_sites( this_site ) ),'_',num2str(j)] ) );
      saveas( h(j), fname  );
      
  end
    close( h );
end
end


if false
    % all sites & depths integrated NEE
    h_all = plot_kernel_regressions_all_sites( shallow, ...
                                               mid, ...
                                               deep);
    set( h_all, 'Visible', 'On' );
    % integrated NEE
    plot_kernel_regressions( shallow, ...
                             '0-6 cm SWC (cm^3 cm^-^3)', ...
                             '0-6 cm SWC, integrated daily NEE', ...
                             'kernel_regressions_shallow_daily_integrated', ...
                             true );  % if true plot integrated NEE

    plot_kernel_regressions(  mid, ...
                             '6-23 cm SWC (cm^3 cm^-^3)', ...
                             '6-23 cm SWC, integrated daily NEE', ...
                             'kernel_regressions_mid_daily_integrated', ...
                             true );

    plot_kernel_regressions(  deep, ...
                             '23-60 cm SWC (cm^3 cm^-^3)', ...
                             '23-60 cm SWC, integrated daily NEE', ...
                             'kernel_regressions_deep_daily_integrated', ...
                             true );
% 
%     plot_kernel_regressions( deep_20_30_day, ...
%                              '20-30 cm SWC (cm^3 cm^-^3)', ...
%                              '20-30 cm SWC, integrated daytime NEE', ...
%                              'kernel_regressions_deep2030_day_integrated', ...
%                              true );
% 
%     plot_kernel_regressions( deep_30plus_day, ...
%                              '30+ cm SWC (cm^3 cm^-^3)', ...
%                              '30+ cm SWC, integrated daytime NEE', ...
%                              'kernel_regressions_deep30plus_day_integrated', ...
%                              true );

    % plain kernel regression
    plot_kernel_regressions( shallow, ...
                             '0-6 cm SWC (cm^3 cm^-^3)', ...
                             '0-6 cm SWC, daily NEE', ...
                             'kernel_regressions_shallow_daily', ...
                             false );  % if false plot integrated NEE

    plot_kernel_regressions( mid, ...
                             '6-23 cm SWC (cm^3 cm^-^3)', ...
                             '6-23 cm SWC, daily NEE', ...
                             'kernel_regressions_mid_daily', ...
                             false );

    plot_kernel_regressions( deep, ...
                             '23-60 cm SWC (cm^3 cm^-^3)', ...
                             '23-60 cm SWC, daily NEE', ...
                             'kernel_regressions_deep_dilay', ...
                             false );

%     plot_kernel_regressions( deep_20_30_day, ...
%                              '20-30 cm SWC (cm^3 cm^-^3)', ...
%                              '20-30 cm SWC, daytime NEE', ...
%                              'kernel_regressions_deep2030_day', ...
%                              false );
% 
%     plot_kernel_regressions( deep_30plus_day, ...
%                              '30+ cm SWC (cm^3 cm^-^3)', ...
%                              '30+ cm SWC, daytime NEE', ...
%                              'kernel_regressions_deep30plus_day', ...
%                              false );

h_fig =...
    plot_kernel_regressions_single_site(...
    surface_data{1,1}.surfaces.shallow,...
    surface_data{1,1}.surfaces.mid,...
    surface_data{1,1}.surfaces.deep,...
    surface_data{1,1}.clim_spaces.shallow);
end
save('surface_data.mat','surface_data')