% options this should have:  kernel regressions or histogram only; use saved
% data or not

%clear all
%close all

% calculate the T--SWC--NEE histograms, kernel regressions, and climate space
% surfaces
load_stored_data = false;
surface_data = Kernel_regression_Tim( load_stored_data );

for this_site = 1:6
    h_fig = plot( surface_data{ this_site } );
    fname = fullfile( 'C:\Code\KernelRegressions\plots', ...                                         
                      sprintf( '%s.eps', char( UNM_sites( this_site ) ) ) );
    figure_2_eps( h_fig, fname );
    close( h_fig );
    
end

if false
    % all sites & depths integrated NEE
    h_all = plot_kernel_regressions_all_sites( shallow_night, ...
                                               shallow_day, ...
                                               deep_10_20_day, ...
                                               deep_20_30_day, ...
                                               deep_30plus_day )
    set( h_all, 'Visible', 'On' );
    % integrated NEE
    plot_kernel_regressions( shallow_night, ...
                             '0-5 cm SWC (cm^3 cm^-^3)', ...
                             '0-5 cm SWC, integrated nighttime NEE', ...
                             'kernel_regressions_shallow_night_integrated', ...
                             true );  % if true plot integrated NEE

    plot_kernel_regressions( shallow_day, ...
                             '0-5 cm SWC (cm^3 cm^-^3)', ...
                             '0-5 cm SWC, integrated daytime NEE', ...
                             'kernel_regressions_shallow_day_integrated', ...
                             true );

    plot_kernel_regressions( deep_10_20_day, ...
                             '10-20 cm SWC (cm^3 cm^-^3)', ...
                             '10-20 cm SWC, integrated daytime NEE', ...
                             'kernel_regressions_deep1020_day_integrated', ...
                             true );

    plot_kernel_regressions( deep_20_30_day, ...
                             '20-30 cm SWC (cm^3 cm^-^3)', ...
                             '20-30 cm SWC, integrated daytime NEE', ...
                             'kernel_regressions_deep2030_day_integrated', ...
                             true );

    plot_kernel_regressions( deep_30plus_day, ...
                             '30+ cm SWC (cm^3 cm^-^3)', ...
                             '30+ cm SWC, integrated daytime NEE', ...
                             'kernel_regressions_deep30plus_day_integrated', ...
                             true );

    % plain kernel regression
    plot_kernel_regressions( shallow_night, ...
                             '0-5 cm SWC (cm^3 cm^-^3)', ...
                             '0-5 cm SWC, nighttime NEE', ...
                             'kernel_regressions_shallow_day', ...
                             false );  % if false plot integrated NEE

    plot_kernel_regressions( shallow_day, ...
                             '0-5 cm SWC (cm^3 cm^-^3)', ...
                             '0-5 cm SWC, daytime NEE', ...
                             'kernel_regressions_shallow_day', ...
                             false );

    plot_kernel_regressions( deep_10_20_day, ...
                             '10-20 cm SWC (cm^3 cm^-^3)', ...
                             '10-20 cm SWC, daytime NEE', ...
                             'kernel_regressions_deep1020_day', ...
                             false );

    plot_kernel_regressions( deep_20_30_day, ...
                             '20-30 cm SWC (cm^3 cm^-^3)', ...
                             '20-30 cm SWC, daytime NEE', ...
                             'kernel_regressions_deep2030_day', ...
                             false );

    plot_kernel_regressions( deep_30plus_day, ...
                             '30+ cm SWC (cm^3 cm^-^3)', ...
                             '30+ cm SWC, daytime NEE', ...
                             'kernel_regressions_deep30plus_day', ...
                             false );
end