function h_fig = plot_kernel_regressions_all_sites( shallow_night, ...
                                                  shallow_day, ...
                                                  deep1, deep2, deep3 )
% PLOT_KERNEL_REGRESSIONS_BY_SITE - plot kernel regression results,
%   one column per site

h_fig = figure( 'Units', 'Inches', ...
                'Position', [ 0, 0, 24, 13 ], ...
                'Visible', 'off' );

for this_site = 1:6
    leftmost = ( this_site == 1 );

    this_ax = subplotrc( 5, 6, 1, this_site );    
    scale_term = shallow_night{ this_site }.n_count;
    plot( shallow_night{ this_site }, ...
          'main_title', char( shallow_night{ this_site }.sitecode ), ...
          'ax', this_ax, ...
          'cbar_lab', 'NEE', ...
          'scale_term', scale_term );
    if leftmost; ylabel( '0-5 cm SWC (cm^3 cm^-^3)' ); end
    
    this_ax = subplotrc( 5, 6, 2, this_site );    
    scale_term = shallow_day{ this_site }.n_count;
    plot( shallow_day{ this_site }, ...
          'main_title', char( shallow_day{ this_site }.sitecode ), ...
          'ax', this_ax, ...
          'cbar_lab', 'NEE', ...
          'scale_term', scale_term );
    if leftmost; ylabel( '0-5 cm SWC (cm^3 cm^-^3)' ); end
    
    this_ax = subplotrc( 5, 6, 3, this_site );    
    scale_term = deep1{ this_site }.n_count;
    plot( deep1{ this_site }, ...
          'main_title', char( deep1{ this_site }.sitecode ), ...
          'ax', this_ax, ...
          'cbar_lab', 'NEE', ...
          'scale_term', scale_term );
    if leftmost; ylabel( '10-20 cm SWC (cm^3 cm^-^3)' ); end
    
    this_ax = subplotrc( 5, 6, 4, this_site );    
    scale_term = deep2{ this_site }.n_count;
    plot( deep2{ this_site }, ...
          'main_title', char( deep2{ this_site }.sitecode ), ...
          'ax', this_ax, ...
          'cbar_lab', 'NEE', ...
          'scale_term', scale_term );
    if leftmost; ylabel( '20-30 cm SWC (cm^3 cm^-^3)' ); end
    
    this_ax = subplotrc( 5, 6, 5, this_site );    
    scale_term = deep3{ this_site }.n_count;
    plot( deep3{ this_site }, ...
          'main_title', char( deep3{ this_site }.sitecode ), ...
          'ax', this_ax, ...
          'cbar_lab', 'NEE', ...
          'scale_term', scale_term );
    xlabel( 'Mean air temp (^oC)' );
    if leftmost; ylabel( '30+ cm SWC (cm^3 cm^-^3)' ); end
end

fname = fullfile( getenv( 'PLOTS' ), ...
                  'KernelRegressions', ...
                  'all_sites_depths.eps' );
figure_2_eps( h_fig, fname );