function h_fig = plot_kernel_regressions_all_sites( shallow, ...
                                                    mid, ...
                                                    deep) 
% PLOT_KERNEL_REGRESSIONS_BY_SITE - plot kernel regression results,
%   one column per site

h_fig = figure( 'Units', 'Inches', ...
                'Position', [ 0, 0, 24, 13 ], ...
                'Visible', 'off' );

for this_site = 1:6
    leftmost = ( this_site == 1 );

    this_ax = subplotrc( 3, 6, 1, this_site );    
    scale_term = shallow{ this_site }.n_count;
    plot( shallow{ this_site }, ...
          'main_title', char( shallow{ this_site }.sitecode ), ...
          'ax', this_ax, ...
          'cbar_lab', 'NEE', ...
          'scale_term', scale_term );
    if leftmost; ylabel( '0-6 cm SWC (cm^3 cm^-^3)' ); end
    
    this_ax = subplotrc( 3, 6, 2, this_site );    
    scale_term = mid{ this_site }.n_count;
    plot( mid{ this_site }, ...
          'main_title', char( mid{ this_site }.sitecode ), ...
          'ax', this_ax, ...
          'cbar_lab', 'NEE', ...
          'scale_term', scale_term );
    if leftmost; ylabel( '6-23 cm SWC (cm^3 cm^-^3)' ); end
    
    this_ax = subplotrc( 3, 6, 3, this_site );    
    scale_term = deep{ this_site }.n_count;
    plot( deep{ this_site }, ...
          'main_title', char( deep{ this_site }.sitecode ), ...
          'ax', this_ax, ...
          'cbar_lab', 'NEE', ...
          'scale_term', scale_term );
    if leftmost; ylabel( '23-60 cm SWC (cm^3 cm^-^3)' ); end
end % Plots

fname = fullfile( getenv( 'PLOTS' ), ...
                  'KernelRegressions', ...
                  'all_sites_depths.eps' );
figure_2_eps( h_fig, fname );